### ISSUE TITLE
Triggers twice in safari when three-finger drag is enabled

### ISSUE THREAD

**Issue by maxim-toleutai** [rxhanson/Middle-Community#52]
After enabling three-finger drag (in Accessability), in Safari and in some other applications, with three-finger clicks or taps, it works twice (for example, opens two tabs at a time).
![](https://im4.ezgif.com/tmp/ezgif-4-a9fc466a15.gif)
When three-finger drag is turned off, everything works fine.

It would be great to be able to use both functionalities.

Spec: MacBook Pro, M1 Max, macOS 12.5

**Comment by rxhanson** [comment]
Unfortunately, this is a macOS limitation. There is no way to distinguish a click executed by three finger drag from a click triggered by an actual click, so there's no way to treat them differently and properly react to a three finger drag as a 3rd party.

If you try to configure three finger click in Middle when three finger drag is enabled, there should be a warning shown. If you already have three finger click enabled in Middle, then you enable three finger drag, there won't be a warning displayed since Middle doesn't constantly poll that setting.

(Thanks for reporting this! I'm closing it out, though, since there's nothing that can be done from my side).
