### ISSUE TITLE
One Finger Force Touch triggers additional Mouse1 event in Firefox

### ISSUE THREAD

**Issue by Hylian** [rxhanson/Middle-Community#67]
Hello,

I'm trying out Middle, and really enjoying the One Finger Force Touch option!

However, in Firefox, this appears to trigger both a Mouse1 and Mouse3 event. eg. If I force touch a link, it will simultaneously open it in the new tab, as well as the current. Other options, such as Three Finger Click, seem to work as expected. I was wondering if this is a known issue, and whether you could look into it.

Middle Version: 1.8.2 (89)
Firefox Version: Nightly 123.0a1 (Build ID: 20240105211306)
Hardware: MacBook Pro 14" (2021)
macOS Version: Sonoma 14.2.1

Thank you!

**Comment by rxhanson** [comment]
Thanks for trying out Middle! Unfortunately, this is an inherent limitation on how this works, so it's really only good in scenarios where you're ok with a left click being executed first. Since a Force Touch always starts with a left mouse down, Middle would have to prevent the left mouse down from propagating, then add it back in if no Force Touch occurred. The delay incurred would be unbearable. If only there were a way to skip the initial mouse down for a touch that immediately exerted higher pressure on the trackpad, then we'd be able to work around this.

**Comment by Hylian** [comment]
Gotcha, thanks for the info! It's unfortunate, because it seems like Safari handles it fine, but I assume that's because Safari's already force touch-aware.
